"use server";

import { createHash } from "crypto";
import { mkdir, writeFile } from "fs/promises";
import path from "path";
import PDFDocument from "pdfkit";
import { getServerSession } from "next-auth/next";

import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

async function getOwnedDraft(draftId: string) {
  const session = await getServerSession(authOptions);
  const email = session?.user?.email;

  if (!email) throw new Error("Unauthorized");

  const user = await prisma.user.findUnique({
    where: { email },
    select: { id: true },
  });

  if (!user) throw new Error("User profile not found");

  const draft = await prisma.filingDraft.findFirst({
    where: { id: draftId, userId: user.id },
    select: { id: true, userId: true },
  });

  if (!draft) throw new Error("Filing draft not found");

  return draft;
}

function buildPacketPdf(snapshotJson: string) {
  return new Promise<Buffer>((resolve, reject) => {
    const document = new PDFDocument({ margin: 48 });
    const chunks: Buffer[] = [];

    document.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", reject);

    const snapshot = JSON.parse(snapshotJson) as {
      filing: {
        taxYear: number;
        filerType: string | null;
        businessStructure: string | null;
        taxableIncome?: number | null;
        taxPayable?: number | null;
        refundDue?: number | null;
        reconciliationGap?: number | null;
      };
      documents: { documentType: string; fileName: string }[];
      ledgerEntries: {
        entryType: string;
        category: string | null;
        description: string;
        amount: number;
      }[];
    };

    document.fontSize(20).text("TaxRocket Filing Packet", { underline: true });
    document.moveDown();
    document.fontSize(11).text(`Tax Year: ${snapshot.filing.taxYear}`);
    document.text(`Filer: ${snapshot.filing.filerType ?? "Not specified"}`);
    document.text(
      `Business structure: ${snapshot.filing.businessStructure ?? "Not specified"}`,
    );

    document.moveDown();
    document.fontSize(14).text("Tax Summary");
    document.fontSize(11).text(
      `Taxable income: PKR ${(snapshot.filing.taxableIncome ?? 0).toLocaleString()}`,
    );
    document.text(
      `Tax payable: PKR ${(snapshot.filing.taxPayable ?? 0).toLocaleString()}`,
    );
    document.text(
      `Refund due: PKR ${(snapshot.filing.refundDue ?? 0).toLocaleString()}`,
    );
    document.text(
      `Reconciliation gap: PKR ${Math.abs(snapshot.filing.reconciliationGap ?? 0).toLocaleString()}`,
    );

    document.moveDown();
    document.fontSize(14).text("Ledger Entries");
    document.fontSize(10);
    if (snapshot.ledgerEntries.length === 0) {
      document.text("No ledger entries recorded.");
    } else {
      for (const entry of snapshot.ledgerEntries) {
        document.text(
          `${entry.entryType} | ${entry.category ?? "—"} | ${entry.description} | PKR ${entry.amount.toLocaleString()}`,
        );
      }
    }

    document.moveDown();
    document.fontSize(14).text("Attached Documents");
    document.fontSize(10);
    if (snapshot.documents.length === 0) {
      document.text("No documents attached.");
    } else {
      for (const file of snapshot.documents) {
        document.text(`${file.documentType}: ${file.fileName}`);
      }
    }

    document.moveDown();
    document.fontSize(9).fillColor("#666666").text(
      "Generated by TaxRocket. This packet is a snapshot for user review.",
    );
    document.end();
  });
}

export async function getLatestFilingPacketAction(draftId: string) {
  try {
    const draft = await getOwnedDraft(draftId);
    const packet = await prisma.filingPacket.findFirst({
      where: {
        filingDraftId: draft.id,
        userId: draft.userId,
      },
      orderBy: { version: "desc" },
      select: {
        id: true,
        version: true,
        packetHash: true,
        status: true,
        approvalStatus: true,
        taxPayable: true,
        refundDue: true,
        fileUrl: true,
        createdAt: true,
      },
    });

    return {
      success: true,
      packet: packet
        ? {
            ...packet,
            pdfUrl: packet.fileUrl ? `/api/packets/${packet.id}` : null,
          }
        : null,
    };
  } catch (error) {
    console.error("Error fetching filing packet:", error);
    return { success: false, error: "Failed to fetch filing packet" };
  }
}

export async function generateFilingPacketAction(draftId: string) {
  try {
    const draft = await getOwnedDraft(draftId);
    const [draftData, documents, ledgerEntries, latestPacket] =
      await Promise.all([
        prisma.filingDraft.findUnique({
          where: { id: draft.id },
          select: {
            taxYear: true,
            status: true,
            filerType: true,
            businessStructure: true,
            incomeSources: true,
            readinessChecks: true,
            openingWealth: true,
            closingWealth: true,
            reconciliationGap: true,
            reconciliationStatus: true,
            reconciliationMethod: true,
            reconciliationNote: true,
            taxableIncome: true,
            taxWithheld: true,
            taxPayable: true,
            refundDue: true,
            taxCalculationStatus: true,
          },
        }),
        prisma.document.findMany({
          where: {
            filingDraftId: draft.id,
            userId: draft.userId,
          },
          select: {
            documentType: true,
            fileName: true,
            mimeType: true,
            sizeBytes: true,
            extractionStatus: true,
          },
        }),
        prisma.ledgerEntry.findMany({
          where: {
            filingDraftId: draft.id,
            userId: draft.userId,
          },
          orderBy: { createdAt: "asc" },
          select: {
            entryDate: true,
            entryType: true,
            category: true,
            description: true,
            amount: true,
            source: true,
          },
        }),
        prisma.filingPacket.findFirst({
          where: {
            filingDraftId: draft.id,
            userId: draft.userId,
          },
          orderBy: { version: "desc" },
          select: { id: true, version: true, approvalStatus: true },
        }),
      ]);

    if (!draftData) {
      return { success: false, error: "Filing draft not found" };
    }

    const snapshot = {
      generatedAt: new Date().toISOString(),
      filing: {
        ...draftData,
        status:
          latestPacket?.approvalStatus === "APPROVED"
            ? "IN_PROGRESS"
            : draftData.status,
        incomeSources: JSON.parse(draftData.incomeSources),
        readinessChecks: JSON.parse(draftData.readinessChecks),
      },
      documents,
      ledgerEntries,
    };

    const snapshotJson = JSON.stringify(snapshot);
    const packetHash = createHash("sha256")
      .update(snapshotJson)
      .digest("hex");
    const version = (latestPacket?.version ?? 0) + 1;

    const packet = await prisma.$transaction(async (tx) => {
      if (latestPacket?.approvalStatus === "APPROVED") {
        await tx.filingPacket.update({
          where: { id: latestPacket.id },
          data: {
            approvalStatus: "SUPERSEDED",
            status: "SUPERSEDED",
          },
        });

        await tx.filingDraft.update({
          where: { id: draft.id },
          data: { status: "IN_PROGRESS" },
        });
      }

      return tx.filingPacket.create({
        data: {
          filingDraftId: draft.id,
          userId: draft.userId,
          version,
          packetHash,
          snapshotJson,
          status: "GENERATED",
          approvalStatus: "PENDING",
          taxPayable: draftData.taxPayable ?? 0,
          refundDue: draftData.refundDue ?? 0,
        },
        select: {
          id: true,
          version: true,
          packetHash: true,
          status: true,
          approvalStatus: true,
          taxPayable: true,
          refundDue: true,
          createdAt: true,
        },
      });
    });

    return { success: true, packet };
  } catch (error) {
    console.error("Error generating filing packet:", error);
    return { success: false, error: "Failed to generate filing packet" };
  }
}

export async function generateFilingPacketPdfAction(draftId: string) {
  try {
    const draft = await getOwnedDraft(draftId);
    const packet = await prisma.filingPacket.findFirst({
      where: {
        filingDraftId: draft.id,
        userId: draft.userId,
      },
      orderBy: { version: "desc" },
    });

    if (!packet) {
      return { success: false, error: "Generate a packet snapshot first" };
    }

    const pdfBuffer = await buildPacketPdf(packet.snapshotJson);
    const packetDirectory = path.join(process.cwd(), "uploads", "packets");
    await mkdir(packetDirectory, { recursive: true });

    const storedFileName = `${packet.id}.pdf`;
    await writeFile(path.join(packetDirectory, storedFileName), pdfBuffer);

    const fileUrl = `packets/${storedFileName}`;
    await prisma.filingPacket.update({
      where: { id: packet.id },
      data: { fileUrl },
    });

    return {
      success: true,
      pdfUrl: `/api/packets/${packet.id}`,
      version: packet.version,
    };
  } catch (error) {
    console.error("Error generating filing packet PDF:", error);
    return { success: false, error: "Failed to generate filing packet PDF" };
  }
}
